GET http://localhost:5102/api/

###
POST http://localhost:5102/api/campaigns
Content-Type: application/json

{
  "Name": "Test Place",
  "Fraction": "Test Fraction",
  "PlayerNote": "Test Note",
  "DmNote": "Test Dm Note",
  "Description": "Test Description",
  "CampaignId": 1
}
